server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/luisurpay7/microservicios-spring-boot-cloud
          search-paths: config-data
  application:
    name: config-service